
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ .Release.Name }}-smtp-secrets
data:
  EMAIL_HOST_PASSWORD: {{ .Values.smtp.password | default "" | b64enc | quote}}
---

apiVersion: v1
kind: ConfigMap
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ .Release.Name }}-smtp-vars
data:
  EMAIL_HOST: {{ .Values.smtp.host | default "" | quote}}
  EMAIL_HOST_USER: {{ .Values.smtp.user | default "" | quote}}
  EMAIL_PORT: {{ .Values.smtp.port | default 587 | quote}}
  EMAIL_FROM: {{ .Values.smtp.from | default "Plane Mailer <team@mailer.example.com>"}}
  EMAIL_USE_TLS: {{ .Values.smtp.use_tls | default 1 | quote}}
  EMAIL_USE_SSL: {{ .Values.smtp.use_ssl | default 0 | quote}}

