
apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ .Release.Name }}-web
  labels:
    app.name: {{ .Release.Namespace }}-{{ .Release.Name }}-web
spec:
  clusterIP: None
  ports:
  - name: web-3000
    port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app.name: {{ .Release.Namespace }}-{{ .Release.Name }}-web

---

apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ .Release.Name }}-web-wl
spec:
  replicas: {{ .Values.web.replicas | default 3}}
  selector:
    matchLabels:
      app.name: {{ .Release.Namespace }}-{{ .Release.Name }}-web
  template:
    metadata:
      namespace: {{ .Release.Namespace }}
      labels:
        app.name: {{ .Release.Namespace }}-{{ .Release.Name }}-web
    spec:
      containers:
      - name: {{ .Release.Name }}-web
        imagePullPolicy: Always
        image: {{ .Values.dockerhub.images.frontend | default "makeplane/plane-frontend" }}:{{ .Values.planeVersion }}
        stdin: true
        tty: true
        resources:
          limits:
            memory: {{ .Values.web.memoryLimit  | default "100Mi" | quote }}
            cpu: {{ .Values.web.cpuLimit | default "200m" | quote}}
        command:
          - /usr/local/bin/start.sh
        args:
          - web/server.js
          - web
      serviceAccount: {{ .Release.Name }}-srv-account
      serviceAccountName: {{ .Release.Name }}-srv-account

---