apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ .Release.Name }}-ingress
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: {{ .Values.ingress.clientMaxBodySize | default "5m" | quote }}
spec:
  ingressClassName: {{ .Values.ingress.ingressClass }}
  rules:
    - host: {{ .Values.ingress.appHost }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Release.Name }}-web
                port:
                  number: 3000
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: {{ .Release.Name }}-api
                port:
                  number: 8000
          - path: /spaces
            pathType: Prefix
            backend:
              service:
                name: {{ .Release.Name }}-space
                port:
                  number: 3000
          {{- if .Values.minio.local_setup }}
          - path: /{{ .Values.env.docstore_bucket }}
            pathType: Prefix
            backend:
              service:
                name: {{ .Release.Name }}-minio
                port:
                  number: 9000
          {{- end }}
    {{- if and .Values.minio.local_setup .Values.ingress.minioHost }}
    - host: {{ .Values.ingress.minioHost }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Release.Name }}-minio
                port:
                  number: 9090
    {{- end }}
  tls:
    {{- if .Values.ssl.useOwnCert }}
    - hosts:
      - {{ .Values.ingress.appHost | quote }}
      {{- if .Values.ingress.minioHost }}
      - {{ .Values.ingress.minioHost | quote }}
      {{- end }}
      secretName: betanum
    {{- end }}
